
# Core.h
# -----------------------------------------------------------------------------

# The top-level container for all other LLVM Intermediate Representation (IR)
# objects.
struct LLVMOpaqueModule { }

# Represents an individual value in LLVM IR.
struct LLVMOpaqueValue { }

# Each value in the LLVM IR has a type
struct LLVMOpaqueType { }

# Represents a basic block of instructions in LLVM IR.
struct LLVMOpaqueBasicBlock { }

# Represents an LLVM basic block builder.
struct LLVMOpaqueBuilder { }

# Destroy a module instance.
extern let LLVMDisposeModule(*LLVMOpaqueModule);

# Dispose of internally allocated memory.
extern let LLVMDisposeMessage(str);

# Create a new, empty module in the global context.
extern let LLVMModuleCreateWithName(str) -> *LLVMOpaqueModule;

# Return a string representation of the module.
extern let LLVMPrintModuleToString(*LLVMOpaqueModule) -> str;

# Set the data layout for a module.
extern let LLVMSetDataLayout(*LLVMOpaqueModule, str);

# Set the target triple for a module.
extern let LLVMSetTarget(*LLVMOpaqueModule, str);

# Add a function to a module under a specified name.
extern let LLVMAddFunction(*LLVMOpaqueModule, name: str, *LLVMOpaqueType)
    -> *LLVMOpaqueValue;

# Obtain an integer type from the global context with a specified bit
# width.
extern let LLVMInt1Type() -> *LLVMOpaqueType;
extern let LLVMInt8Type() -> *LLVMOpaqueType;
extern let LLVMInt16Type() -> *LLVMOpaqueType;
extern let LLVMInt32Type() -> *LLVMOpaqueType;
extern let LLVMInt64Type() -> *LLVMOpaqueType;
extern let LLVMIntType(uint32) -> *LLVMOpaqueType;

# Obtain the length of an array type.
extern let LLVMGetArrayLength(*LLVMOpaqueType) -> uint32;

# Create a pointer type that points to a defined type.
extern let LLVMPointerType(*LLVMOpaqueType, uint32) -> *LLVMOpaqueType;

# Obtain a function type consisting of a specified signature.
extern let LLVMFunctionType(
    *LLVMOpaqueTargetData, *LLVMOpaqueTargetData, uint32, uint32)
        -> *LLVMOpaqueType;

# Obtain the parameter at the specified index.
extern let LLVMGetParam(*LLVMOpaqueValue, index: uint) -> *LLVMOpaqueValue;

# Append a basic block to the end of a function using the global context.
extern let LLVMAppendBasicBlock(*LLVMOpaqueValue, name: str)
    -> *LLVMOpaqueBasicBlock;

# Obtain a constant value for an integer type.
extern let LLVMConstInt(*LLVMOpaqueType, uint128, bool) -> *LLVMOpaqueValue;

# Instruction builders
extern let LLVMCreateBuilder() -> *LLVMOpaqueBuilder;
extern let LLVMDisposeBuilder(*LLVMOpaqueBuilder);
extern let LLVMPositionBuilderAtEnd(*LLVMOpaqueBuilder, *LLVMOpaqueBasicBlock);
extern let LLVMGetInsertBlock(*LLVMOpaqueBuilder) -> *LLVMOpaqueBuilder;
extern let LLVMBuildCall(*LLVMOpaqueBuilder, *LLVMOpaqueValue,
                         *LLVMOpaqueValue, uint,
                         str) -> *LLVMOpaqueValue;
extern let LLVMBuildRetVoid(*LLVMOpaqueBuilder) -> *LLVMOpaqueValue;
extern let LLVMBuildRet(*LLVMOpaqueBuilder, *LLVMOpaqueValue) -> *LLVMOpaqueValue;


# TargetMachine.h
# -----------------------------------------------------------------------------

struct LLVMOpaqueTargetMachine { }

struct LLVMTarget { }

# Creates a new llvm::TargetMachine. See llvm::Target::createTargetMachine
extern let LLVMCreateTargetMachine(
    *LLVMTarget, str, str, str, int32, int32, int32)
        -> *LLVMOpaqueTargetMachine;

# Dispose the LLVMTargetMachineRef instance generated by
# LLVMCreateTargetMachine.
extern let LLVMDisposeTargetMachine(*LLVMOpaqueTargetMachine);

# Get a triple for the host machine as a string. The result needs to be
# disposed with LLVMDisposeMessage.
extern let LLVMGetDefaultTargetTriple() -> str;

# Finds the target corresponding to the given triple and stores it in \p T.
# Returns 0 on success. Optionally returns any error in ErrorMessage.
# Use LLVMDisposeMessage to dispose the message.
extern let LLVMGetTargetFromTriple(str, *LLVMTarget, *str) -> int32;

# Returns the llvm::DataLayout used for this llvm:TargetMachine.
extern let LLVMGetTargetMachineData(*LLVMOpaqueTargetMachine)
    -> *LLVMOpaqueTargetData;

# Target.h
# -----------------------------------------------------------------------------

struct LLVMOpaqueTargetData { }

extern let LLVMInitializeX86Target();
extern let LLVMInitializeX86TargetInfo();

# Converts target data to a target layout string.
extern let LLVMCopyStringRepOfTargetData(*LLVMOpaqueTargetData) -> str;
